---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name:  external-secrets
  namespace: flux-system
spec:
  interval: 15s
  timeout: 1m0s
  url: https://charts.external-secrets.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 1m
  targetNamespace: external-secrets
  releaseName: "external-secrets"
  chart:
    spec:
      chart: external-secrets
      version: "0.15.0"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      interval: 24h
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      remediateLastFailure: true
  driftDetection:
    mode: enabled
  values:
    crds:
      install: true
    tls:
      # -- Start the true controller that injects the CA into mutating and validating webhooks, and CRD as well.
      enableController: true
      # -- When cert-manager is disabled, Capsule will generate the TLS certificate for webhook and CRDs conversion.
      create: true
    manager:
      options:
        capsuleUserGroups:
        - "system:serviceaccounts:capsule-argo-addon"
        forceTenantPrefix: false
