apiVersion: addons.projectcapsule.dev/v1alpha1
kind: SopsSecret
metadata:
    name: vault-multi-secret
spec:
    secrets:
        - name: vault-multi-secret-1
          labels:
            label1: value1
          stringData:
            data-name0: ENC[AES256_GCM,data:6p5yR+dAaQCkKvU=,iv:SDeniGOz5iUWEhJ7byawruCea6yKHj1Z/2n98xaLbS4=,tag:4rVqXjHLDqvtflGKQkRZKg==,type:str]
          data:
            data-name1: ENC[AES256_GCM,data:QbQ14NGazyjoE5rtpVilnw==,iv:Vs0RaG6k9dgQa7KyscJkcJBSmQUFRh1R8IJ3HYiU1jA=,tag:tF/rUZ1oCl6fk4btKiVOpA==,type:str]
sops:
    shamir_threshold: 1
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
        - vault_address: http://openbao.openbao.svc.cluster.local:8200
          engine_path: sops
          key_name: key-1
          created_at: "2025-05-16T21:41:52Z"
          enc: vault:v1:Qs7TZBNXlB8prgDTm+DTH71LN4SiPqb0+9uYgoELPp4oyXreTw+bWA0MPBheATxWA+5eTz+r0B2yJlpi
        - vault_address: http://openbao.openbao.svc.cluster.local:8200
          engine_path: sops
          key_name: key-2
          created_at: "2025-05-16T21:41:52Z"
          enc: vault:v1:9HM++5m/o2I9N5LKd5qu6c8yZWuiMk0Ro5n/T2Wv979bPUxThHCb6Wti7vxx6EyKBvS3aiLzKJdNvYe4
    age: []
    lastmodified: "2025-05-16T21:42:02Z"
    mac: ENC[AES256_GCM,data:VFVK8Wd2A86kgwi+xhLzS25TFzpGr+gpSFuLtXQQpAK+nk27ip26VppMTP4SU1bWDW6XjbW8Ojdsyj20zkM5aX6EZkEjfPC+y4aI2xdJNh9eQ+jMSH8cUQigdDIZOJFsqQmf/T3CZ6WJ5rVty/0R5VYJIH95iPSqP7C1gH2j0rQ=,iv:8nZHM+j/hyh99whTZLNPzXT08BO6KqaXROH6e7GEPDM=,tag:RQbHnNwls0sE2jl3P+Vdig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
