---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: trivy-operator
  namespace: "flux-system"
spec:
  interval: 24h0m0s
  url: https://aquasecurity.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: trivy-operator
  namespace: "flux-system"
spec:
  interval: 30s
  serviceAccountName: kustomize-controller
  releaseName: "trivy-operator"
  targetNamespace: "trivy-system"
  storageNamespace: "trivy-system"
  chart:
    spec:
      chart: trivy-operator
      version: "0.25.0"
      sourceRef:
        kind: HelmRepository
        name: trivy-operator
      interval: 24h
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      remediateLastFailure: true
  driftDetection:
    mode: enabled