---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: capsule
spec:
  interval: 10m
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/projectcapsule/charts/capsule
  ref:
    tag: 0.7.4
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: capsule
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 15s
  targetNamespace: capsule-system
  releaseName: "capsule"
  chartRef:
    kind: OCIRepository
    name: capsule
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      remediateLastFailure: true
  driftDetection:
    mode: disabled
  values:
    proxy:
      enabled: true
      certManager:
        generateCertificates: true
        certificate:
          ipAddresses:
          - 127.0.0.1
          dnsNames:
          - localhost
      service:
        type: NodePort
        nodePort: 30443
      options:
        generateCertificates: false
        extraArgs:
          - "--feature-gates=ProxyClusterScoped=true"
          - "--feature-gates=ProxyAllNamespaced=true"
    crds:
      install: true
    tls:
      # -- Start the true controller that injects the CA into mutating and validating webhooks, and CRD as well.
      enableController: true
      # -- When cert-manager is disabled, Capsule will generate the TLS certificate for webhook and CRDs conversion.
      create: true
    manager:
      options:
        capsuleUserGroups:
        - "projectcapsule.dev"
        forceTenantPrefix: false
