---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: dex
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.dexidp.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dex
  namespace: flux-system
spec:
  interval: 10m
  serviceAccountName: kustomize-controller
  targetNamespace: dex
  chart:
    spec:
      chart: dex
      version: "0.24.1"
      sourceRef:
        kind: HelmRepository
        name: dex
      interval: 1h
  install:
    createNamespace: true
    remediation:
      retries: -1
  values:
    replicaCount: 1
    service:
      type: NodePort
      ports:
        http:
          port: 5556
          targetPort: 5556
          nodePort: 32556
    ingress:
      enabled: false
    config:
      # Replace NODE_IP_OR_DNS with an address reachable from:
      # - your workstation/browser
      # - the kube-apiserver host/node
      issuer: "${DEX_URL}"
      storage:
        type: kubernetes
        config:
          inCluster: true

      web:
        http: 0.0.0.0:5556

      oauth2:
        skipApprovalScreen: true

      enablePasswordDB: true

      staticClients:
        - id: kubernetes
          name: Kubernetes
          secret: kubernetes-secret
          redirectURIs:
            - "$GANGPLANK_URL/*"
            - "$PROXY_URL/*"
            - "$HEADLAMP_URL/*"
      staticPasswords:
        - email: admin@example.com
          username: admin
          userID: 08a8684b-db88-4b73-90a9-3cd1661f5466
          # bcrypt hash for password: "password"
          hash: "$2y$10$XeBzckzHiPe6yRWkJr6r4uSxujj9Pc/XVtoqd6giOgYHF9jPN79oO"
          groups:
            - cluster-admins