---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name:  sops-operator
  namespace: flux-system
spec:
  type: "oci"
  interval: 15s
  timeout: 1m0s
  url: oci://ghcr.io/peak-scale/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sops-operator
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 30s
  targetNamespace: sops-operator
  releaseName: "sops-operator"
  chart:
    spec:
      chart: sops-operator
      version: "0.4.2"
      sourceRef:
        kind: HelmRepository
        name: sops-operator
      interval: 24h
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      remediateLastFailure: true
  driftDetection:
    mode: enabled