---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name:  harbor
  namespace: flux-system
spec:
  interval: 15s
  timeout: 1m0s
  url: https://helm.goharbor.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 15s
  targetNamespace: harbor-system
  releaseName: "harbor"
  chart:
    spec:
      chart: harbor
      version: "1.16.2"
      sourceRef:
        kind: HelmRepository
        name: harbor
      interval: 24h
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      remediateLastFailure: true
  driftDetection:
    mode: disabled
  values:
    expose:
      type: nodePort
      tls.enabled: false
      nodePort.ports.http.nodePort: "30080"
      nodePort.ports.https.nodePort: "30443"
