---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name:  projectcapsule
  namespace: flux-system
spec:
  interval: 1m0s
  timeout: 1m0s
  url: https://projectcapsule.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: capsule-proxy
spec:
  interval: 10m
  dependsOn:
    - name: capsule
  targetNamespace: capsule-system
  releaseName: "capsule-proxy"
  chart:
    spec:
      chart: capsule-proxy
      version: "0.9.0"
      sourceRef:
        kind: HelmRepository
        name: projectcapsule
      interval: 24h
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      remediateLastFailure: true
  driftDetection:
    mode: enabled
  values:
    service:
      type: ClusterIP
    resources: {}
    options:
      logLevel: 10
      enableSSL: true
      generateCertificates: false
      authPreferredTypes: "BearerToken"
      extraArgs:
      - "--feature-gates=ProxyClusterScoped=false"
      - "--feature-gates=ProxyAllNamespaced=true"
      clientConnectionQPS: 50
      clientConnectionBurst: 100
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: capsule
  namespace: flux-system
spec:
  interval: 30s
  targetNamespace: capsule-system
  releaseName: "capsule"
  chart:
    spec:
      chart: capsule
      version: "0.9.0"
      sourceRef:
        kind: HelmRepository
        name: projectcapsule
      interval: 24h
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      remediateLastFailure: true
  driftDetection:
    mode: disabled
  values:
    crds:
      install: true
    tls:
      # -- Start the true controller that injects the CA into mutating and validating webhooks, and CRD as well.
      enableController: true
      # -- When cert-manager is disabled, Capsule will generate the TLS certificate for webhook and CRDs conversion.
      create: true
    manager:
      options:
        forceTenantPrefix: false