---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name:  sops-secrets-operator
  namespace: flux-system
spec:
  interval: 15s
  timeout: 1m0s
  url: https://isindir.github.io/sops-secrets-operator/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sops-secrets-operator
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 30s
  targetNamespace: sops
  releaseName: "sops-secrets-operator"
  chart:
    spec:
      chart: sops-secrets-operator
      version: "0.21.0"
      sourceRef:
        kind: HelmRepository
        name: sops-secrets-operator
      interval: 24h
  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    remediation:
      remediateLastFailure: true
  driftDetection:
    mode: enabled
  values:
    gpg:
      enabled: true
      secret1: sops-gpg
      secret2: sops-gpg
